# Generated by Django 4.0.4 on 2022-06-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('validade', models.CharField(max_length=100)),
            ],
        ),
    ]
