# Generated by Django 4.0.4 on 2022-06-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriminacao', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('enderecoCobranca', models.CharField(max_length=100)),
                ('numNota', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
            ],
        ),
    ]
